// Generated by Selenium IDE
const { Builder, By, Key, until } = require('selenium-webdriver')
const assert = require('assert')

describe('Verificación de tablas', function() {
  this.timeout(30000)
  let driver
  let vars
  beforeEach(async function() {
    driver = await new Builder().forBrowser('chrome').build()
    vars = {}
  })
  afterEach(async function() {
    await driver.quit();
  })
  it('Verificación de tablas', async function() {
    // Test name: Verificación de tablas
    // Step # | name | target | value
    // 1 | open | / | 
    await driver.get("http://localhost:3000/")
    // 2 | setWindowSize | 1280x800 | 
    await driver.manage().window().setRect({ width: 1280, height: 800 })
    // 3 | click | css=.input:nth-child(2) | 
    await driver.findElement(By.css(".input:nth-child(2)")).click()
    // 4 | click | css=.input:nth-child(3) | 
    await driver.findElement(By.css(".input:nth-child(3)")).click()
    // 5 | click | css=.input:nth-child(4) | 
    await driver.findElement(By.css(".input:nth-child(4)")).click()
    // 6 | click | css=li:nth-child(1153) | 
    await driver.findElement(By.css("li:nth-child(1153)")).click()
    // 7 | click | css=.enviar | 
    await driver.findElement(By.css(".enviar")).click()
    // 8 | close |  | 
    await driver.close()
  })
})
